### ISSUE TITLE
ERROR: unsupported operand type(s) for +=: 'NoneType' and 'int'  

### ISSUE THREAD

**Issue by amarand** [hughrun/ephemetoot#66]
**Does your proposal relate to...**

- [x] a new flag (option)

**Is your feature request related to a problem? Please describe.**
I am able to redirect standard and error output using cron - which I still haven't gotten working yet, but I'm working on it. Was wondering if you might be able to create a --log flag which would take a specific directory/filename argument, which would make cron a lot easier. Of course, you could also have that same thing inside the configuration file, which would make the cron entry even cleaner.

**Describe the solution you'd like**
I'd like either (or both) a --log flag that takes a directory and/or full path with filename for all log output. I rotate my files every day with Linux, so that should be fine, regardless the size.

**Would like to write the code yourself?**

- [x] I would like someone else to write the code

**Describe alternatives you've considered**
I've used the standard and error redirect in cron, but it doesn't seem to update like it should?

**Additional context**
Please forgive me if I've missed something terribly obvious here!

**Comment by hughrun** [comment]
Hey @amarand can you provide more information- perhaps your cron job text and further explanation of what doesn't seem right about your logs?

I am currently doing exactly what you suggest with no problem: directing logs to a specific file which is rotated with logrotate. Could possibly be a quick fix with your `cron` line.

**Comment by amarand** [comment]
I think it may just be a weird timing/caching thing? Where the output isn't being written directly to the file, but after it finishes, it does?

I did a run with the following cron entry:

57 9 * * * /home/sgoodman/.local/bin/ephemetoot --config '/home/sgoodman/.local/bin/config.yaml' --datestamp --pace --retry-mins 5 >> /home/sgoodman/logs/ephemetoot.log 2>&1

It did eventually write to the file, deleting 200 or so toots, then ending with the following error:

ERROR: unsupported operand type(s) for +=: 'NoneType' and 'int'

(I think there were significantly more toots to delete.)

**Comment by hughrun** [comment]
hmm that looks like it's probably an `ephemetoot` error rather than a logging error.

I'm on holiday at the moment, will take a look next week. Any further details would be great.

**Comment by amarand** [comment]
No stress at all!

I had just upgraded from 2.6 to 3.1, and did a full uninstall, then reinstall, using pip3 as you mentioned to me before, so let me know if there's anything you need me to do when you get back.

**Comment by hughrun** [comment]
I had a brief look and my suspicion is that this is caused by `retry_on_error` if `attempts` somehow ends up with a null value or maybe `process_toot` if `deleted_count` ends up with a null value. I can't see any obvious way this would happen, but I admit I haven't really looked deeply into it. Sounds like something is failing after ephemetoot has run for a long time, which may mean e.g. a process gets rebooted or the network cuts out partway through, causing an error.

I'll try to take a close look at this later in the week.

**Comment by hughrun** [comment]
@amarand sorry for the delay on this.

Can you please install [version 3.1.1a1](https://github.com/hughrun/ephemetoot/releases/tag/v3.1.1a1) prerelease and test it to see if it resolves your problem, and let me know how it goes?

You should be able to just install it over the top of your current version using:

```
pip install ephemetoot==3.1.1a1
```

Because this is a pre-release you need to explicitly state the version, otherwise pip will install version 3.1.0.

**Comment by hughrun** [comment]
@amarand have you had a chance to test this?

**Comment by amarand** [comment]
> 
> 
> @amarand have you had a chance to test this?

So sorry to have missed this! I had a nice, high fever yesterday after my second vaccination shot. Will look into this today. Thanks!

**Comment by hughrun** [comment]
yikes! take it easy, no rush 🙂

**Comment by amarand** [comment]
Worked perfectly, thank you! Just finished deleting 1,000 toots!

**Comment by hughrun** [comment]
Fantastic! Thanks for confirming, and congratulations on your vax shots 💉
